package com.sjl.stroop.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sjl.stroop.model.pojo.PersonData;

import com.sjl.stroop.dao.PersonDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig personDataDaoConfig;

    private final PersonDataDao personDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        personDataDaoConfig = daoConfigMap.get(PersonDataDao.class).clone();
        personDataDaoConfig.initIdentityScope(type);

        personDataDao = new PersonDataDao(personDataDaoConfig, this);

        registerDao(PersonData.class, personDataDao);
    }
    
    public void clear() {
        personDataDaoConfig.clearIdentityScope();
    }

    public PersonDataDao getPersonDataDao() {
        return personDataDao;
    }

}
