package com.sjl.stroop.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.sjl.stroop.model.pojo.PersonData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PERSON_DATA".
*/
public class PersonDataDao extends AbstractDao<PersonData, Void> {

    public static final String TABLENAME = "PERSON_DATA";

    /**
     * Properties of entity PersonData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Idcard = new Property(0, String.class, "idcard", false, "IDCARD");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property Birth = new Property(2, String.class, "birth", false, "BIRTH");
        public final static Property Gender = new Property(3, String.class, "gender", false, "GENDER");
        public final static Property Job = new Property(4, String.class, "job", false, "JOB");
        public final static Property Education = new Property(5, String.class, "education", false, "EDUCATION");
        public final static Property StroopA = new Property(6, String.class, "stroopA", false, "STROOP_A");
        public final static Property StroopB = new Property(7, String.class, "stroopB", false, "STROOP_B");
        public final static Property StroopC = new Property(8, String.class, "stroopC", false, "STROOP_C");
        public final static Property StroopState = new Property(9, boolean.class, "stroopState", false, "STROOP_STATE");
    }


    public PersonDataDao(DaoConfig config) {
        super(config);
    }
    
    public PersonDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PERSON_DATA\" (" + //
                "\"IDCARD\" TEXT," + // 0: idcard
                "\"NAME\" TEXT," + // 1: name
                "\"BIRTH\" TEXT," + // 2: birth
                "\"GENDER\" TEXT," + // 3: gender
                "\"JOB\" TEXT," + // 4: job
                "\"EDUCATION\" TEXT," + // 5: education
                "\"STROOP_A\" TEXT," + // 6: stroopA
                "\"STROOP_B\" TEXT," + // 7: stroopB
                "\"STROOP_C\" TEXT," + // 8: stroopC
                "\"STROOP_STATE\" INTEGER NOT NULL );"); // 9: stroopState
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PERSON_DATA\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PersonData entity) {
        stmt.clearBindings();
 
        String idcard = entity.getIdcard();
        if (idcard != null) {
            stmt.bindString(1, idcard);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String birth = entity.getBirth();
        if (birth != null) {
            stmt.bindString(3, birth);
        }
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(4, gender);
        }
 
        String job = entity.getJob();
        if (job != null) {
            stmt.bindString(5, job);
        }
 
        String education = entity.getEducation();
        if (education != null) {
            stmt.bindString(6, education);
        }
 
        String stroopA = entity.getStroopA();
        if (stroopA != null) {
            stmt.bindString(7, stroopA);
        }
 
        String stroopB = entity.getStroopB();
        if (stroopB != null) {
            stmt.bindString(8, stroopB);
        }
 
        String stroopC = entity.getStroopC();
        if (stroopC != null) {
            stmt.bindString(9, stroopC);
        }
        stmt.bindLong(10, entity.getStroopState() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PersonData entity) {
        stmt.clearBindings();
 
        String idcard = entity.getIdcard();
        if (idcard != null) {
            stmt.bindString(1, idcard);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(2, name);
        }
 
        String birth = entity.getBirth();
        if (birth != null) {
            stmt.bindString(3, birth);
        }
 
        String gender = entity.getGender();
        if (gender != null) {
            stmt.bindString(4, gender);
        }
 
        String job = entity.getJob();
        if (job != null) {
            stmt.bindString(5, job);
        }
 
        String education = entity.getEducation();
        if (education != null) {
            stmt.bindString(6, education);
        }
 
        String stroopA = entity.getStroopA();
        if (stroopA != null) {
            stmt.bindString(7, stroopA);
        }
 
        String stroopB = entity.getStroopB();
        if (stroopB != null) {
            stmt.bindString(8, stroopB);
        }
 
        String stroopC = entity.getStroopC();
        if (stroopC != null) {
            stmt.bindString(9, stroopC);
        }
        stmt.bindLong(10, entity.getStroopState() ? 1L: 0L);
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public PersonData readEntity(Cursor cursor, int offset) {
        PersonData entity = new PersonData( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // idcard
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // name
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // birth
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // gender
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // job
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // education
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // stroopA
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // stroopB
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // stroopC
            cursor.getShort(offset + 9) != 0 // stroopState
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PersonData entity, int offset) {
        entity.setIdcard(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBirth(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setGender(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setJob(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setEducation(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setStroopA(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setStroopB(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setStroopC(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setStroopState(cursor.getShort(offset + 9) != 0);
     }
    
    @Override
    protected final Void updateKeyAfterInsert(PersonData entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(PersonData entity) {
        return null;
    }

    @Override
    public boolean hasKey(PersonData entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
